### ISSUE TITLE
Planned activities for 0.3

### ISSUE THREAD

**Issue by bedantaguru** [r-rudra/tidycells#14]
These are the planned activity for 0.3.0
These are in progress in [nightly](https://github.com/bedantaguru/tidycells_nightly)
Few of these may be dropped (as all of these are experimental)

- [ ] Complete Heuristic maturation phase 1 : complete https://github.com/r-rudra/tidycells/issues/5 
- [ ] Introduce grammar
- [ ] _%<^%_ kind of symbols for NNE etc.
- [ ] Add shinytest prototype as described in https://github.com/r-rudra/tidycells/issues/13
- [ ] Compatibility of cell traceback with external operations (like **{unpivotr}** etc)
- [ ] Multi routes tests
- [ ] Optional packages availability based test
- [ ] Mark cell-analysis for remodelling into a state (maybe in later version)
- [ ] {DT} based table plots - check https://github.com/r-rudra/tidycells/issues/16 
- [ ] reveal.js – Presentation for various topics
- [ ] {pkgdown} tweaks [like all tables to DT etc]
- [ ] Explore [Github Actions](https://github.com/features/actions) as guided in [this](https://speakerdeck.com/jimhester/github-actions-for-r?slide=54). Also check https://github.com/r-rudra/tidycells/issues/18
- [ ] Fix all issues tagged as [bug](https://github.com/r-rudra/tidycells/labels/Bug) like ( https://github.com/r-rudra/tidycells/issues/20 )

**Comment by bedantaguru** [comment]
Also, follow a release routine for stability in the release process.

**Comment by bedantaguru** [comment]
Here are a few references for 

> {DT} based table plots

- There is an option to select cells in native DataTable (see [this link](https://datatables.net/extensions/select/examples/initialisation/cells.html))
- There is an option in DT that works with shiny only (sample of development code given below)
- Most likely native DataTable option is not going to work in DT and Shiny (Here are references for that)
  - https://github.com/rstudio/DT/issues/305
  - https://github.com/rstudio/DT/pull/717
  - https://github.com/rstudio/DT/pull/743

```r
require(tidycells)
require(DT)

xl <- tidyxl::xlsx_cells("inst/extdata/marks.xlsx")
fmt <-tidyxl::xlsx_formats("inst/extdata/marks.xlsx")

cd <- as_cell_df(xl)

cdd <- as.data.frame(cd)

require(shiny)

std_opts <- list(
  pageLength = 10,
  keys = TRUE,
  sDom = '<"top">lrt<"bottom">pB',
  deferRender = TRUE,
  #scrollX = TRUE,
  scrollX= 400,
  scrollY = 500,
  scroller = TRUE,
  scrollCollapse = TRUE,
  ordering = FALSE,
  fixedColumns = TRUE,
  fixedHeader = TRUE
)


runGadget(shinyApp(
  ui = fluidPage(DTOutput("dt")),
  server = function(input, output){
    output$dt <- renderDT({
      datatable(cdd,
                escape = FALSE,
                rownames = TRUE,
                style = "bootstrap",
                fillContainer = FALSE,
                class = "cell-border stripe",
                extensions = c("KeyTable", "Scroller","FixedHeader"),
                selection = list(target = 'cell'),
                #editable = TRUE,
                options = std_opts)
    })
  }
))

```

I'll test it and keep a watch on the same.

**Comment by bedantaguru** [comment]
Just tested this feature as mentioned [here ](https://rstudio.github.io/DT/extensions.html) it is still not well connected to shiny. Hence going ahead with DT option. Maybe in later versions of DT this feature will be implemented. 

(Here is the comment on this from DT developer)

> DT has its own implementation of row/column/cell selections in Shiny, which is very different from the Select extension. In particular, the Select extension is unlikely to work in the server-side processing mode. On the other hand, DT’s implementation does not allow multiple selections via the Shift/Ctrl keys at the moment.

**Comment by bedantaguru** [comment]
It **[DT and Shiny with Select Extension]** seems doable. However, this should be kept as an optional feature.
